import { Product, Testimonial } from "@/types";

// ============================================================
// MOCK PRODUCT DATA — Replace with Firestore queries
// ============================================================

export const mockProducts: Product[] = [
  // NECKLACES
  {
    id: "nk-001",
    name: "Pearl Dream Necklace",
    price: 349,
    originalPrice: 499,
    category: "Necklaces",
    images: ["/images/products/necklace-1.jpg", "/images/products/necklace-1b.jpg"],
    description: "A delicate pearl necklace with tiny star charms. Handmade with real freshwater pearls and silver-plated chain. Perfect for everyday wear.",
    badge: "BESTSELLER",
    rating: 4.8,
    reviewCount: 124,
    inStock: true,
    tags: ["pearl", "star", "minimal"],
    createdAt: "2024-12-01",
  },
  {
    id: "nk-002",
    name: "Kawaii Bear Chain",
    price: 299,
    category: "Necklaces",
    images: ["/images/products/necklace-2.jpg"],
    description: "Adorable teddy bear pendant on a dainty chain. The bear charm is hand-painted and sealed with gloss. Ultra cute!",
    badge: "NEW",
    rating: 4.9,
    reviewCount: 67,
    inStock: true,
    tags: ["bear", "kawaii", "pendant"],
    createdAt: "2025-01-15",
  },
  {
    id: "nk-003",
    name: "Pastel Star Layered Set",
    price: 549,
    originalPrice: 699,
    category: "Necklaces",
    images: ["/images/products/necklace-3.jpg"],
    description: "A gorgeous 2-layer necklace set with pastel star and moon charms. Sold as a set — wear together or separately.",
    badge: "SALE",
    rating: 4.7,
    reviewCount: 89,
    inStock: true,
    tags: ["layered", "star", "moon", "pastel"],
    createdAt: "2024-11-20",
  },

  // BRACELETS
  {
    id: "br-001",
    name: "Milky Beaded Bracelet",
    price: 199,
    category: "Bracelets",
    images: ["/images/products/bracelet-1.jpg"],
    description: "Soft pastel milky white beads with a tiny heart charm. Stretchy and comfortable fit. Handmade with love.",
    badge: "BESTSELLER",
    rating: 4.9,
    reviewCount: 203,
    inStock: true,
    tags: ["beaded", "heart", "pastel"],
    createdAt: "2024-10-05",
  },
  {
    id: "br-002",
    name: "Pink Crystal Charm Bracelet",
    price: 449,
    originalPrice: 599,
    category: "Bracelets",
    images: ["/images/products/bracelet-2.jpg"],
    description: "Stunning pink crystal beads with stainless steel charms. Includes star, flower, and moon charms.",
    badge: "NEW",
    rating: 4.8,
    reviewCount: 45,
    inStock: true,
    tags: ["crystal", "charm", "pink"],
    createdAt: "2025-01-10",
  },
  {
    id: "br-003",
    name: "Hello Kitty Friendship Bracelet",
    price: 249,
    category: "Bracelets",
    images: ["/images/products/bracelet-3.jpg"],
    description: "Cute Hello Kitty charm on a soft bead stretch bracelet. Perfect gift for your bestie!",
    rating: 4.7,
    reviewCount: 112,
    inStock: true,
    tags: ["kitty", "friendship", "cute"],
    createdAt: "2024-09-15",
  },

  // EARRINGS
  {
    id: "er-001",
    name: "Daisy Stud Earrings",
    price: 149,
    category: "Earrings",
    images: ["/images/products/earring-1.jpg"],
    description: "Tiny daisy flower studs in soft pastel enamel. Nickel-free and hypoallergenic. Available in pink, lavender, and white.",
    badge: "BESTSELLER",
    rating: 4.9,
    reviewCount: 178,
    inStock: true,
    tags: ["daisy", "stud", "hypoallergenic"],
    createdAt: "2024-08-20",
  },
  {
    id: "er-002",
    name: "Star Dangle Earrings",
    price: 229,
    category: "Earrings",
    images: ["/images/products/earring-2.jpg"],
    description: "Sparkly star charm dangle earrings with crystal accents. Light and comfortable to wear all day.",
    badge: "NEW",
    rating: 4.6,
    reviewCount: 54,
    inStock: true,
    tags: ["star", "dangle", "crystal"],
    createdAt: "2025-01-05",
  },

  // KEYCHAINS
  {
    id: "kc-001",
    name: "Plushie Bunny Keychain",
    price: 199,
    category: "Keychains",
    images: ["/images/products/keychain-1.jpg"],
    description: "Tiny soft plushie bunny keychain — so squishy and cute! Comes in pink, white, and lavender.",
    badge: "BESTSELLER",
    rating: 4.8,
    reviewCount: 156,
    inStock: true,
    tags: ["bunny", "plushie", "soft"],
    createdAt: "2024-07-10",
  },
  {
    id: "kc-002",
    name: "Beaded Charm Keychain",
    price: 249,
    category: "Keychains",
    images: ["/images/products/keychain-2.jpg"],
    description: "Handmade beaded keychain with kawaii charms — mushroom, heart, and star. Customizable!",
    badge: "NEW",
    rating: 4.7,
    reviewCount: 82,
    inStock: true,
    tags: ["beaded", "charm", "custom"],
    createdAt: "2025-01-20",
  },

  // BOWS
  {
    id: "bw-001",
    name: "Satin Coquette Bow",
    price: 129,
    category: "Bows",
    images: ["/images/products/bow-1.jpg"],
    description: "Luxurious satin bow hair clip in soft pink. Perfect coquette aesthetic accessory. One size fits all.",
    badge: "BESTSELLER",
    rating: 4.9,
    reviewCount: 234,
    inStock: true,
    tags: ["satin", "coquette", "hair"],
    createdAt: "2024-06-01",
  },
  {
    id: "bw-002",
    name: "Pearl Bow Headband",
    price: 299,
    originalPrice: 399,
    category: "Bows",
    images: ["/images/products/bow-2.jpg"],
    description: "Elegant pearl-studded bow headband. A blend of cute and sophisticated. Perfect for photos!",
    badge: "SALE",
    rating: 4.7,
    reviewCount: 91,
    inStock: true,
    tags: ["pearl", "headband", "elegant"],
    createdAt: "2024-11-01",
  },

  // RINGS
  {
    id: "rg-001",
    name: "Butterfly Adjustable Ring",
    price: 149,
    category: "Rings",
    images: ["/images/products/ring-1.jpg"],
    description: "Dainty butterfly charm adjustable ring. Open band, one size fits all. Silver-plated finish.",
    badge: "NEW",
    rating: 4.8,
    reviewCount: 67,
    inStock: true,
    tags: ["butterfly", "adjustable", "silver"],
    createdAt: "2025-01-12",
  },
  {
    id: "rg-002",
    name: "Flower Midi Ring Set",
    price: 299,
    category: "Rings",
    images: ["/images/products/ring-2.jpg"],
    description: "Set of 3 dainty flower midi rings in gold-plated finish. Stack them your way!",
    badge: "BESTSELLER",
    rating: 4.9,
    reviewCount: 108,
    inStock: true,
    tags: ["flower", "set", "midi", "gold"],
    createdAt: "2024-09-05",
  },

  // PHONE CHARMS
  {
    id: "pc-001",
    name: "Sanrio Phone Charm",
    price: 349,
    originalPrice: 449,
    category: "Phone Charms",
    images: ["/images/products/phonecharm-1.jpg"],
    description: "Kawaii Sanrio character phone charm with pearl beads. Fits all phones with a case loop or port.",
    badge: "BESTSELLER",
    rating: 4.9,
    reviewCount: 189,
    inStock: true,
    tags: ["sanrio", "kawaii", "pearl"],
    createdAt: "2024-08-15",
  },
  {
    id: "pc-002",
    name: "Y2K Bow Phone Charm",
    price: 249,
    category: "Phone Charms",
    images: ["/images/products/phonecharm-2.jpg"],
    description: "Trendy Y2K aesthetic bow phone charm with crystal accents. Makes your phone look adorable!",
    badge: "NEW",
    rating: 4.7,
    reviewCount: 73,
    inStock: true,
    tags: ["y2k", "bow", "crystal"],
    createdAt: "2025-01-18",
  },
];

export const newArrivals = mockProducts.filter((p) =>
  ["nk-002", "br-002", "er-002", "kc-002", "bw-001", "rg-001", "pc-002"].includes(p.id)
);

export const trendingProducts = mockProducts.filter((p) =>
  ["nk-001", "br-001", "er-001", "kc-001", "bw-002", "rg-002", "pc-001"].includes(p.id)
);

export const mockTestimonials: Testimonial[] = [
  {
    id: "t1",
    name: "Priya S.",
    location: "Mumbai",
    rating: 5,
    comment: "Omg I am obsessed with my Milkbead order!! The pearl necklace is so pretty and delicate. Already placed my second order 🌸",
    avatar: "P",
    product: "Pearl Dream Necklace",
  },
  {
    id: "t2",
    name: "Ananya K.",
    location: "Bangalore",
    rating: 5,
    comment: "The packaging alone made me smile SO much. Everything was wrapped in pink tissue with a handwritten note. Quality is amazing!!",
    avatar: "A",
    product: "Milky Beaded Bracelet",
  },
  {
    id: "t3",
    name: "Rhea M.",
    location: "Delhi",
    rating: 5,
    comment: "Got the satin bow and it's literally the cutest thing I own. Fast shipping too! Will definitely be ordering more 💖",
    avatar: "R",
    product: "Satin Coquette Bow",
  },
  {
    id: "t4",
    name: "Zara P.",
    location: "Pune",
    rating: 5,
    comment: "The phone charm is SO AESTHETIC. Everyone keeps asking where I got it from. Milkbead is the best!",
    avatar: "Z",
    product: "Sanrio Phone Charm",
  },
];

export const categoryIcons: Record<string, string> = {
  Necklaces: "✨",
  Bracelets: "💫",
  Earrings: "🌸",
  Keychains: "🔑",
  Bows: "🎀",
  Rings: "💍",
  "Phone Charms": "📱",
};
